version: "3.1"

services:
  db:
    image: postgres:13-alpine
    container_name: blitz-memo-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blitz-memo
    volumes:
      - ./dataDir:/var/lib/postgresql/data
